Feature/accounts 기능 구현
kim-caron/django-instagram pull request #1
Opened 2024-04-22 14:21 UTC by kim-caron

urls.py와 views.py 위주로 구현하였음.
articles, stories, highlight 앱과의 연동을 위해 master와 branch를 합쳐
해당 앱들의 url, view 함수 구현을 우선 진행할 예정

2024-04-22 15:42 UTC, BDlhj requested changes
LGTM(Look Good To Me)~~~👍🏻 요즘 js하느라 정신없을텐데 고생했다!!!

2024-04-22 15:42 UTC, BDlhj commented on accounts/serializers.py
> +class UserSerializer(serializers.ModelSerializer):
기본적으로 class는 두 줄 띄고 작성하는 걸 권장! PEP8 참고하면 좋을듯!

2024-04-22 15:42 UTC, BDlhj commented on accounts/serializers.py
> +class ProfileSerializer(serializers.ModelSerializer):
ditto(위와 같음)

2024-04-22 15:42 UTC, BDlhj commented on accounts/serializers.py
> +        fields = '__all__'
new line

2024-04-22 15:42 UTC, BDlhj commented on accounts/forms.py
> +        model = get_user_model()
여기서 빨간색 표시가 나는 건 맨 마지막 줄에 new line이 없어서 그런거니까 한 줄 띄어주면 돼~!

2024-04-22 15:42 UTC, BDlhj commented on accounts/models.py
> +    '''
크게 상관은 없지만 ERD나 기타 문서에 기록하고 여기에서는 빼주는 게 좋을듯!

2024-04-22 15:42 UTC, BDlhj commented on accounts/models.py
> +    created_at = models.DateField(auto_now_add=True)
new line

2024-04-22 15:42 UTC, BDlhj commented on accounts/models.py
> +    followings = models.ManyToManyField('self',symmetrical=False,related_name='followers')
콤마 뒤에 스페이스 추가

2024-04-22 15:42 UTC, BDlhj commented on accounts/models.py
> +    friend = models.ManyToManyField('self',symmetrical=False,related_name='friendly')
related_name로 명사를 쓰면 좋을듯!

2024-04-22 15:42 UTC, BDlhj commented on accounts/models.py
> +    gender = models.CharField(max_length=10, blank=True, null=True)
django의 문자열 기반 model field들은 null=True 지정을 지양!
[https://docs.djangoproject.com/en/5.0/ref/models/fields/#null](url)

2024-04-22 15:42 UTC, BDlhj commented on accounts/views.py
> +    return redirect('accounts:profile', person.username)
new line

2024-04-22 15:42 UTC, BDlhj commented on accounts/urls.py
여유가 된다면 view와 함께 restful하게 재설계해보는 것도 좋을듯!

2024-04-22 15:42 UTC, BDlhj commented on accounts/views.py
> +# Create your views here.
필요 없는 주석들은 지워주면 깔끔~!

2024-04-22 15:42 UTC, BDlhj commented on instagram/settings.py
> +AUTH_USER_MODEL ='accounts.User'
new line

2024-04-22 15:42 UTC, BDlhj commented on accounts/urls.py
> +    path('emailsignup/', views.signup, name='signup'),
```suggestion
    path('email-signup/', views.signup, name='signup'),
```

2024-04-22 15:42 UTC, BDlhj commented on instagram/urls.py
> +    path('<str:username>/follow/', accounts_views.follow, name='follow'),
accounts app으로 빼면 어떨지 고민해보면 좋을듯!

2024-04-22 15:44 UTC, BDlhj commented on accounts/serializers.py
어라 근데 serializer는 사용되는 곳이 없네?! UserSerializer랑 ProfileSerializer랑 똑같고!?

2024-04-24 11:28 UTC, kim-caron commented on accounts/serializers.py
아직 Response로 처리하는게 익숙치 않아서 ㅜㅜ 공부해오겠슴다!!
마침 JS도 배웠으니, RESTFul하게 수정해볼게~ 늦은 시간에 리뷰 고마워요 호준햄🫶

2024-04-24 11:28 UTC, merged

2024-04-24 13:21 UTC, BDlhj commented on accounts/serializers.py
굿굿~~~!! js하랴 django하랴 정신없겠구만ㅠㅜㅜ 파이팅이야💪🏻🫶